"""Unit tests for the orchestration command-line argument parser."""

import argparse
import unittest
from unittest.mock import patch

from orchestration.cli import parse_orchestration_arguments

PARSER_USAGE_ERROR_CODE = 2


class TestOrchestratorArgumentsParser(unittest.TestCase):
    """Verifies CLI argument parsing and validation rules."""
    base_args: list[str]

    @classmethod
    def setUpClass(cls) -> None:
        """Runs once before all tests in this suite to define shared test data."""
        cls.base_args = [
            "orchestrator.py",
            "--config",
            "conf/experiments/example.yaml",
        ]

    def _assert_system_exit(
        self,
        args_list: list[str],
        exit_code: int = PARSER_USAGE_ERROR_CODE,
    ) -> None:
        """Supporting helper to assert that invalid inputs trigger a SystemExit.

        Args:
            args_list: Simulated terminal elements representing sys.argv.
            exit_code: The expected status code integer generated by SystemExit.
        """
        with self.assertRaises(SystemExit) as context, patch("sys.argv", args_list):
            parse_orchestration_arguments()

        self.assertEqual(context.exception.code, exit_code)

    def test_parser_accepts_valid_config_flag(self) -> None:
        """Ensure a valid --config path is correctly parsed into a Namespace."""
        with patch("sys.argv", self.base_args):
            args = parse_orchestration_arguments()

        self.assertIsInstance(args, argparse.Namespace)
        self.assertEqual(args.config, "conf/experiments/example.yaml")

    def test_parser_missing_config_argument(self) -> None:
        """Ensure the parser raises SystemExit (code 2) when --config is omitted."""
        test_args = self.base_args.copy()
        del test_args[1:3]
        self._assert_system_exit(args_list=test_args)

    def test_parser_missing_config_value(self) -> None:
        """Ensure the parser raises SystemExit (code 2) when --config value is missing."""
        test_args = self.base_args.copy()
        test_args.pop(2)
        self._assert_system_exit(args_list=test_args)

    def test_parser_rejects_unsupported_flag(self) -> None:
        """Ensure the parser rejects an unknown or unregistered flag."""
        wrong_arg = [
            "orchestrator.py",
            "--unsupported",
            "conf/experiments/example.yaml",
        ]
        self._assert_system_exit(args_list=wrong_arg)


if __name__ == "__main__":
    unittest.main()
